In [1]:
import pandas as pd
import numpy as np

In [2]:
np.random.seed(9)

In [3]:
df = pd.read_csv("Bank_Personal_Loan_Modelling.csv")

In [4]:
df

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  \
0        1   25           1      49     91107       4    1.6          1   
1        2   45          19      34     90089       3    1.5          1   
2        3   39          15      11     94720       1    1.0          1   
3        4   35           9     100     94112       1    2.7          2   
4        5   35           8      45     91330       4    1.0          2   
...    ...  ...         ...     ...       ...     ...    ...        ...   
4995  4996   29           3      40     92697       1    1.9          3   
4996  4997   30           4      15     92037       4    0.4          1   
4997  4998   63          39      24     93023       2    0.3          3   
4998  4999   65          40      49     90034       3    0.5          2   
4999  5000   28           4      83     92612       3    0.8          1   

      Mortgage  Personal Loan  Securities Account  CD Account  Online  \
0            0              0                   1           0       0   
1            0              0                   1           0       0   
2            0              0                   0           0       0   
3            0              0                   0           0       0   
4            0              0                   0           0       0   
...        ...            ...                 ...         ...     ...   
4995         0              0                   0           0       1   
4996        85              0                   0           0       1   
4997         0              0                   0           0       0   
4998         0              0                   0           0       1   
4999         0              0                   0           0       1   

      CreditCard  
0              0  
1              0  
2              0  
3              0  
4              1  
...          ...  
4995           0  
4996           0  
4997           0  
4998           0  
4999           1  

[5000 rows x 14 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   ID                  5000 non-null   int64  
 1   Age                 5000 non-null   int64  
 2   Experience          5000 non-null   int64  
 3   Income              5000 non-null   int64  
 4   ZIP Code            5000 non-null   int64  
 5   Family              5000 non-null   int64  
 6   CCAvg               5000 non-null   float64
 7   Education           5000 non-null   int64  
 8   Mortgage            5000 non-null   int64  
 9   Personal Loan       5000 non-null   int64  
 10  Securities Account  5000 non-null   int64  
 11  CD Account          5000 non-null   int64  
 12  Online              5000 non-null   int64  
 13  CreditCard          5000 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 547.0 KB


In [6]:
print(min(df["Experience"]))
df["Experience"] = abs(df["Experience"])
min(df["Experience"])

-3


0

In [7]:
df.corr()["Personal Loan"]

ID                   -0.024801
Age                  -0.007726
Experience           -0.008304
Income                0.502462
ZIP Code              0.000107
Family                0.061367
CCAvg                 0.366889
Education             0.136722
Mortgage              0.142095
Personal Loan         1.000000
Securities Account    0.021954
CD Account            0.316355
Online                0.006278
CreditCard            0.002802
Name: Personal Loan, dtype: float64

In [8]:
df = df.drop(["ZIP Code","ID"], axis = 1)

In [9]:
min_class = df[df["Personal Loan"] == 1]
maj_class = df[df["Personal Loan"] == 0][:len(min_class)]

In [10]:
df = pd.concat([min_class,maj_class])

In [11]:
df

Age  Experience  Income  Family  CCAvg  Education  Mortgage  \
9     34           9     180       1   8.90          3         0   
16    38          14     130       4   4.70          3       134   
18    46          21     193       2   8.10          3         0   
29    38          13     119       1   3.30          2         0   
38    42          18     141       3   5.00          3         0   
..   ...         ...     ...     ...    ...        ...       ...   
526   26           2     205       1   6.33          1       271   
527   33           8      65       2   0.10          1        89   
529   39          15      82       1   0.80          2         0   
530   54          30      21       2   0.20          1         0   
531   32           6      50       4   2.10          3         0   

     Personal Loan  Securities Account  CD Account  Online  CreditCard  
9                1                   0           0       0           0  
16               1                   0           0       0           0  
18               1                   0           0       0           0  
29               1                   0           1       1           1  
38               1                   1           1       1           0  
..             ...                 ...         ...     ...         ...  
526              0                   0           0       0           1  
527              0                   0           0       1           0  
529              0                   0           0       1           0  
530              0                   0           0       0           1  
531              0                   1           1       1           1  

[960 rows x 12 columns]

In [12]:
y = df["Personal Loan"]
x = df.drop('Personal Loan' , axis=1) 

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler()
x= scaler.fit_transform(x)

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size=0.2, random_state=0)

# NN

In [17]:
def dense(inputs,weights,bias,size = (11,1)):
    y = 0
    y = np.dot(weights,inputs.T) + bias
    # a network of single neuron for the sake of simplicity
    return y 

In [18]:
def sigmoid(x):
    return 1.0/(1.0 + np.exp(-x))

In [19]:
def lossfn(y_true, y_pred):
    # loss function BinaryCrossEntropy Loss
    num = (1-y_true) * np.log(1 - y_pred + 1e-7)
    den = y_true * np.log(y_pred + 1e-7)
    return -np.mean(num+den, axis=0)

## Optimising weights using PSO

In [20]:
from pso import PSO

In [21]:
weights = PSO(lossfn, dense, y_train.values,x_train)

[10.535526028881613, 6.380079468087672, 5.939350287397406, 8.793596409962941, 6.275143948875704, 5.372698483652776, 10.430590509669644, 6.48501498729964, 7.17758941409863, 6.1911955335061295]
[10.388616301984857, 5.057891926016873, 4.86900799143533, 6.275143948875704, 4.092485149266765, 4.323343291533096, 5.267762964440808, 5.120853237544054, 4.827033783750543, 5.5615824182343205]
[10.388616301984857, 5.057891926016873, 4.86900799143533, 6.275143948875704, 4.092485149266765, 4.323343291533096, 5.267762964440808, 5.120853237544054, 4.827033783750543, 5.5615824182343205]
[9.612093459816291, 4.848020887592937, 4.86900799143533, 5.036904822174479, 4.092485149266765, 4.323343291533096, 4.848020887592937, 4.848020887592937, 4.827033783750543, 5.120853237544054]
[9.612093459816291, 4.848020887592937, 4.86900799143533, 5.036904822174479, 4.092485149266765, 4.323343291533096, 4.848020887592937, 4.848020887592937, 4.827033783750543, 5.120853237544054]
[7.639305698631291, 4.701111160696181, 4.869

In [23]:
weights.position

array([2.61216074, 2.94439681, 3.10553076, 2.27293501, 3.27429876,
       1.89291423, 2.44174758, 2.16832568, 2.39139514, 2.54923695,
       2.63341439, 2.50285998])

In [25]:
from sklearn.metrics import classification_report

In [27]:
pso_ypred = np.round(sigmoid(dense(x_test , weights.position[:11] , weights.position[11:])))

In [28]:
print(classification_report(pso_ypred , y_test.values))

              precision    recall  f1-score   support

         0.0       0.63      0.78      0.70        82
         1.0       0.80      0.65      0.72       110

    accuracy                           0.71       192
   macro avg       0.71      0.72      0.71       192
weighted avg       0.73      0.71      0.71       192



## Optimising weights using ACO

In [30]:
from aco import optimize_weights

In [50]:
weights = optimize_weights(x_train, y_train.values, num_ants=12, num_iterations=100, evaporation_rate=0.01, alpha=0.01, beta=1, layer = dense)

In [51]:
weights

(array([-0.28090212,  0.55672637,  0.32272999, -0.17085808,  0.86497459,
         0.81634937,  0.54581185, -0.10358381,  0.61278702,  0.40085602,
         0.14502572, -0.16120906]),
 3.6517559685764986)

In [52]:
aco_ypred = np.round(sigmoid(dense(x_train , weights[0][:11] , weights[0][11:])))

In [53]:
print(classification_report(aco_ypred , y_train.values))

              precision    recall  f1-score   support

         0.0       0.86      0.73      0.79       443
         1.0       0.70      0.84      0.76       325

    accuracy                           0.78       768
   macro avg       0.78      0.79      0.78       768
weighted avg       0.79      0.78      0.78       768



## Optimising weights using Genetic Algorithm

In [35]:
from gen import GeneticAlgorithm

In [36]:
population = np.random.uniform(-1, 1, size=(12, 12))

In [37]:
ga = GeneticAlgorithm(population,y_train, x_train, dense, n_parents=12, crossover_rate=1, mutation_rate=0.001, n_generations=900)


In [38]:
best_weights, best_fitness = ga.evolve()

In [39]:
best_weights

array([ 0.67102065, -0.52146305, -0.0525961 ,  0.40781406,  0.23192615,
        0.71447522,  0.58210846, -0.08932653,  0.5881094 , -0.16964384,
        0.73029768, -0.82049439])

In [40]:
gen_ypred = np.round(sigmoid(dense(x_train , best_weights[:11], best_weights[-1])))

In [41]:
print(classification_report(gen_ypred , y_train.values))

              precision    recall  f1-score   support

         0.0       0.88      0.58      0.70       568
         1.0       0.39      0.77      0.52       200

    accuracy                           0.63       768
   macro avg       0.63      0.67      0.61       768
weighted avg       0.75      0.63      0.65       768

